version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    build:
      context: frontend
    restart: always
    volumes:
      - "./frontend/resources:/app/resources"
  stt_en:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.en
    restart: always
    volumes:
      - "./frontend/resources/logs/stt_en:/opt/logs"
  stt_de:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.de
    restart: always
    volumes:
      - "./frontend/resources/logs/stt_de:/opt/logs"
  tts:
    build:
      context: tts
      dockerfile: Dockerfile.marytts
    restart: always
  dictate:
    build:
      context: dictate
    restart: always
